INSERT INTO dataset_versions VALUES ('sprint8-v2',CAST(strftime('%s','now') AS INTEGER)*1000,
  'CORE_NUMERIC_V2_FULL_SIGNAL_TIERED','LIVE_BUCKETS_V1','BOUNDED_5PCT_V1',
  'CONSENSUS_V1','FIELD_GROUPS_V1');
