import "dotenv/config";
import { z } from "zod";
import type { SignalPolicy, PriorityPolicy } from "../core/research";
const integer = (fallback: number, min: number, max: number) =>
  z.coerce.number().int().min(min).max(max).default(fallback);
const optionalUrl = z.preprocess((v) => (v === "" ? undefined : v), z.url().optional());
const schema = z.object({
  DATABASE_PATH: z.string().min(1).default("./data/scanner.sqlite"),
  API_PORT: integer(3001, 1024, 65535),
  SCAN_INTERVAL_SECONDS: integer(60, 15, 86400),
  RETENTION_DAYS: integer(0, 0, 36500),
  METEORA_API_URL: z.url().default("https://dlmm.datapi.meteora.ag"),
  METEORA_MIN_TVL: z.coerce.number().nonnegative().default(10000),
  METEORA_MAX_POOLS: integer(1000, 0, 200000),
  METEORA_REQUESTS_PER_SECOND: integer(5, 1, 30),
  GECKO_API_URL: z.url().default("https://api.geckoterminal.com/api/v2"),
  EVM_PAGES: integer(1, 1, 10),
  GECKO_REQUESTS_PER_MINUTE: integer(20, 1, 30),
  BASE_SUBGRAPH_URL: optionalUrl,
  BSC_SUBGRAPH_URL: optionalUrl,
  BASE_RPC_URL: optionalUrl,
  BSC_RPC_URL: optionalUrl,
  BASE_RPC_URLS: z.string().default(""),
  BNB_RPC_URLS: z.string().default(""),
  BSC_LOG_RPC_URLS: z.string().default(""),
  BASE_LIVE_INDEXER_URL: optionalUrl,
  BSC_LIVE_INDEXER_URL: optionalUrl,
  BASE_HISTORICAL_INDEXER_URL: optionalUrl,
  BSC_HISTORICAL_INDEXER_URL: optionalUrl,
  SOLANA_RPC_URLS: z.string().default(""),
  RPC_PROVIDER_REQUESTS_PER_MINUTE: integer(120, 1, 10000),
  RPC_CHAIN_REQUESTS_PER_MINUTE: integer(300, 1, 30000),
  RPC_CALL_TIMEOUT_MS: integer(7000, 500, 30000),
  RPC_PROBE_INTERVAL_SECONDS: integer(1800, 60, 86400),
  BASE_DEPTH_RPC_URL: optionalUrl,
  BSC_FEE_RPC_URL: optionalUrl,
  SOLANA_RPC_URL: optionalUrl,
  ACTIVE_LIQUIDITY_ENABLED: z
    .enum(["true", "false"])
    .default("true")
    .transform((v) => v === "true"),
  ACTIVE_LIQUIDITY_METEORA_LIMIT: integer(40, 0, 1000),
  ACTIVE_LIQUIDITY_EVM_LIMIT: integer(20, 0, 200),
  ACTIVE_LIQUIDITY_MAX_AGE_SECONDS: integer(120, 30, 600),
  ACTIVE_LIQUIDITY_PRICE_MAX_AGE_SECONDS: integer(180, 30, 600),
  ACTIVE_LIQUIDITY_MAX_PRICE_DIVERGENCE: z.coerce.number().min(0.001).max(0.5).default(0.1),
  PRICE_API_URL: z.url().default("https://coins.llama.fi"),
  PRICE_POOL_LIMIT: integer(1000, 0, 1000),
  PRICE_FALLBACK_LIMIT: integer(20, 0, 100),
  PRICE_CONSENSUS_HIGH_DEVIATION_PCT: z.coerce.number().min(0).max(100).default(1),
  PRICE_CONSENSUS_MEDIUM_DEVIATION_PCT: z.coerce.number().min(0).max(100).default(15),
  PRICE_HIGH_AGE_SECONDS: integer(120, 1, 3600),
  PRICE_MEDIUM_AGE_SECONDS: integer(600, 1, 86400),
  PRICE_STABLECOIN_MEDIUM_AGE_SECONDS: integer(900, 1, 86400),
  PRICE_LOW_AGE_SECONDS: integer(1800, 1, 86400),
  PRICE_DISAGREEMENT: z.coerce.number().min(0.001).max(1).default(0.1),
  PRICE_UNAVAILABLE_DISAGREEMENT: z.coerce.number().min(0.001).max(10).default(0.3),
  FEE_EVM_LIMIT: integer(3, 0, 100),
  FEE_MAX_BLOCKS_PER_SCAN: integer(300, 1, 10000),
  BSC_FEE_MAX_BLOCKS_PER_SCAN: integer(900, 1, 10000),
  BASE_LIVE_BOOTSTRAP_BLOCKS: integer(2100,100,20000),
  BSC_LIVE_BOOTSTRAP_BLOCKS: integer(6000,100,30000),
  LIVE_MAX_BLOCKS_PER_JOB: integer(800,10,10000),
  LIVE_POOLS_PER_CYCLE: integer(3,1,40),
  LIVE_INTERVAL_SECONDS: integer(20,5,3600),
  OUTCOME_WORKER_CONCURRENCY: integer(2,1,8),
  OUTCOME_JOBS_PER_CYCLE: integer(100,1,500),
  FEE_CONFIRMATIONS: integer(12, 1, 100),
  FEE_LOG_BLOCK_CHUNK: integer(100, 1, 2000),
  DEPTH_METEORA_LIMIT: integer(5, 0, 100),
  DEPTH_EVM_LIMIT: integer(5, 0, 100),
  DEPTH_REFRESH_SECONDS: integer(600, 60, 3600),
  DEPTH_PRICE_DRIFT_PCT: z.coerce.number().min(0.1).max(20).default(2),
  TOKEN_METADATA_REFRESH_SECONDS: integer(21600, 60, 86400),
  DEPTH_MAX_ARRAYS: integer(32, 1, 128),
  DEPTH_MAX_TICK_WORDS: integer(24, 1, 256),
  DEPTH_MAX_INITIALIZED_TICKS: integer(512, 1, 2048),
  BACKGROUND_INTERVAL_SECONDS: integer(30, 5, 3600),
  ECONOMIC_INTERVAL_SECONDS: integer(120,30,3600),
  STRATEGY_BSC_EXCLUDED: z.enum(["true","false"]).default("false").transform((v)=>v==="true"),
  BACKGROUND_COLD_BUDGET_MS: integer(45000,5000,300000),
  BACKFILL_POOLS_PER_CYCLE: integer(2, 1, 20),
  BACKFILL_MAX_BLOCKS_PER_CYCLE: integer(300, 1, 10000),
  BACKFILL_MAX_RETRIES: integer(5, 1, 100),
  PRICE_BACKFILL_EVENTS_PER_CYCLE: integer(30, 0, 500),
  PRICE_BACKFILL_CALLS_PER_CYCLE: integer(8, 1, 100),
  PRICE_CALLS_PER_MINUTE: integer(20, 1, 1000),
  COHORT_MIN_SAMPLE: integer(30, 1, 10000),
  PRIORITY_TIER1_VOLUME_1H: z.coerce.number().nonnegative().default(50000),
  PRIORITY_TIER2_VOLUME_1H: z.coerce.number().nonnegative().default(5000),
  PRIORITY_TIER2_TVL: z.coerce.number().nonnegative().default(100000),
  SIGNAL_FEE_EFFICIENCY: z.coerce.number().nonnegative().default(0.001),
  SIGNAL_VOLUME_DEPTH: z.coerce.number().nonnegative().default(1),
  SIGNAL_MIN_ACTIVITY: integer(70, 0, 100),
  SIGNAL_MAX_RISK: integer(60, 0, 100),
  SIGNAL_BREAKOUT_PCT: z.coerce.number().nonnegative().default(5),
  SIGNAL_COLLAPSE_PCT: z.coerce.number().nonnegative().default(20),
  ACTIVITY_PERSISTENCE_FRACTION: z.coerce.number().min(0).max(10).default(0.5),
  OUTCOME_MAX_GAP_SECONDS: integer(240, 30, 3600),
  HTTP_TIMEOUT_MS: integer(15000, 100, 120000),
  HTTP_RETRIES: integer(2, 0, 5),
  LOG_LEVEL: z.enum(["fatal", "error", "warn", "info", "debug", "trace", "silent"]).default("info"),
  SURGE_MULTIPLIER: z.coerce.number().min(1.1).default(3),
  SURGE_MIN_HOURLY_FEES: z.coerce.number().nonnegative().default(10),
  ALERT_MIN_ACTIVITY: integer(80, 0, 100),
  ALERT_MAX_RISK: integer(60, 0, 100),
  ALERT_MIN_FEE_EFFICIENCY: z.coerce.number().nonnegative().default(0.001),
  ALERT_COOLDOWN_MINUTES: integer(60, 1, 10080),
  TELEGRAM_BOT_TOKEN: z.string().default(""),
  TELEGRAM_CHAT_ID: z.string().default(""),
  APP_URL: z.url().default("http://localhost:3000"),
});
const result = schema.safeParse(process.env);
if (!result.success)
  throw new Error(
    `Invalid environment: ${result.error.issues.map((i) => i.path.join(".")).join(", ")}`,
  );
export const env = result.data;
export const researchPolicy = (): SignalPolicy => ({
  feeEfficiency: env.SIGNAL_FEE_EFFICIENCY,
  volumeDepth: env.SIGNAL_VOLUME_DEPTH,
  activity: env.SIGNAL_MIN_ACTIVITY,
  risk: env.SIGNAL_MAX_RISK,
  breakoutPct: env.SIGNAL_BREAKOUT_PCT,
  collapsePct: env.SIGNAL_COLLAPSE_PCT,
  persistenceFraction: env.ACTIVITY_PERSISTENCE_FRACTION,
  maxObservationGapMs: env.OUTCOME_MAX_GAP_SECONDS * 1000,
});
export const priorityPolicy = (): PriorityPolicy => ({
  tier1Volume1h: env.PRIORITY_TIER1_VOLUME_1H,
  tier2Volume1h: env.PRIORITY_TIER2_VOLUME_1H,
  tier2Tvl: env.PRIORITY_TIER2_TVL,
});
